# Guardian Spring Boot Starter 配置示例
guardian:
  # 是否启用Guardian功能
  enabled: true

  # 默认计数器类型 (redis, local)
  default-counter-type: redis

  # 默认时间窗口配置
  default-window-size: 1
  default-time-unit: MINUTES
  default-expiration: 180

  # 默认阈值配置
  default-warn-threshold: 10
  default-ban-threshold: 20

  # 其他默认配置
  default-fail-fast: true
  default-error-message: "访问频率过高，请稍后再试"

# Redis配置（如果使用Redis计数器）
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms